name: CI/CD Pipeline

on:
  - push
  - pull_request

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 15432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
          - 3.9
          # YAML, yay https://github.com/actions/runner/issues/1989
          - '3.10'
          - 3.11

    steps:
      - uses: actions/checkout@v2.5.0.5.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PDM
        run: python -m pip install pdm

      - name: Install dependencies
        run: pdm install

      - name: Run tests
        run: pdm run make test

      - name: Run linter
        run: pdm run make lint

      - name: Run mypy
        run: pdm run make mypy

  publish:
    name: Publish package to PyPI
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2.5.0

      - uses: actions/setup-python@v3

      - name: Install PDM
        run: python -m pip install pdm

      - name: Install dependencies
        run: pdm install

      - name: Publish package to PyPI
        run: pdm run make release
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
